"""
DBML to SQLModel schema generator.
Parses schema.dbml and generates:
1. A mermaid ER diagram
2. A schema.py file with SQLModel model classes
"""

import re
from pathlib import Path
from typing import Any


def parse_dbml(filepath: str) -> dict[str, Any]:
    """Parse DBML file and extract table definitions."""
    with open(filepath) as f:
        lines = f.readlines()

    tables = {}
    current_table = None
    in_indexes = False

    for line in lines:
        line = line.strip()

        # Skip empty lines and comments
        if not line or line.startswith("//"):
            continue

        # Table definition
        if line.startswith("Table "):
            current_table = line.split()[1]
            in_indexes = False
            tables[current_table] = {"columns": {}}
            continue

        # Ref definition
        if line.startswith("Ref:"):
            parts = line.replace("Ref:", "").strip().split()
            # Format: from_table.from_col > to_table.to_col
            if len(parts) >= 3:
                from_part = parts[0]
                to_part = parts[2]
                if "." in from_part and "." in to_part:
                    from_table, from_col = from_part.split(".")
                    to_table, to_col = to_part.split(".")
                    if from_table in tables and from_col in tables[from_table]["columns"]:
                        ref = (to_table, to_col)
                        tables[from_table]["columns"][from_col]["ref"] = ref
            continue

        # Skip indexes block
        if "indexes" in line:
            in_indexes = True
            continue

        if in_indexes and line == "}":
            in_indexes = False
            continue

        if in_indexes or line == "}" or not current_table:
            continue

        # Parse column definition
        if current_table and line and not line.startswith("}"):
            # Format: name type [attributes]
            pattern = r"(\w+)\s+(\w+)\s*(?:\[(.*?)\])?"
            match = re.match(pattern, line)
            if match:
                col_name = match.group(1)
                col_type = match.group(2).strip()
                col_attrs = (match.group(3) or "").strip()

                # Determine type
                type_lower = col_type.lower()
                py_type = "int" if type_lower == "int" else "str"

                tables[current_table]["columns"][col_name] = {
                    "type": col_type,
                    "py_type": py_type,
                    "nullable": "not null" not in col_attrs.lower(),
                    "pk": "pk" in col_attrs.lower(),
                    "increment": "increment" in col_attrs.lower(),
                    "ref": None,
                    "attrs": col_attrs,
                }

    return tables


def generate_mermaid_er(tables: dict[str, Any]) -> str:
    """Generate Mermaid ER diagram from tables."""
    mermaid = "erDiagram\n"

    for table_name, table_info in tables.items():
        columns = table_info["columns"]
        mermaid += f"\n    {table_name} {{\n"

        for col_name, col_info in columns.items():
            col_type = col_info["type"].replace("[", "").replace("]", "")
            mermaid += f"        {col_type} {col_name}\n"

        mermaid += "    }\n"

    # Add relationships
    for table_name, table_info in tables.items():
        for col_name, col_info in table_info["columns"].items():
            if col_info["ref"]:
                to_table, to_col = col_info["ref"]
                mermaid += f'    {table_name} ||--o| {to_table} : ""\n'

    return mermaid


def get_python_type(dbml_type: str) -> str:
    """Convert DBML type to Python type hint."""
    type_map = {
        "int": "int",
        "string": "str",
        "text": "str",
        "bigint": "int",
        "smallint": "int",
        "decimal": "float",
        "float": "float",
        "boolean": "bool",
        "datetime": "datetime",
        "date": "date",
        "time": "time",
    }
    return type_map.get(dbml_type.lower(), "str")


def generate_sqlmodel_schema(tables: dict[str, Any]) -> str:
    """Generate SQLModel schema.py from tables."""
    schema = (
        '"""Auto-generated SQLModel schema from schema.dbml.\n'
        "Generated by config/generate_schema.py\n"
        '"""\n\n'
        "from sqlmodel import Field, Relationship, SQLModel\n\n\n"
    )

    # Build a map of which tables have foreign keys pointing to them
    references = {}  # table_name -> list of (from_table, col_name)
    for table_name, table_info in tables.items():
        for col_name, col_info in table_info["columns"].items():
            if col_info["ref"]:
                ref_table, ref_col = col_info["ref"]
                if ref_table not in references:
                    references[ref_table] = []
                references[ref_table].append((table_name, col_name))

    # Helper function to generate plural name
    def pluralize(name: str) -> str:
        if name.endswith("o"):
            return name + "es"
        elif name.endswith("y"):
            return name[:-1] + "ies"
        return name + "s"

    for table_name, table_info in tables.items():
        parts = table_name.split("_")
        class_name = "".join(word.capitalize() for word in parts)
        schema += f"class {class_name}(SQLModel, table=True):\n"
        doc = f'    """Database model for {table_name} table."""\n\n'
        schema += doc

        for col_name, col_info in table_info["columns"].items():
            py_type = get_python_type(col_info["type"])

            # Handle different field types
            if col_info["pk"]:
                py_type = f"{py_type} | None"
                default = " = Field(default=None, primary_key=True)"
            elif col_info["ref"]:
                # Foreign key field
                ref_table, ref_col = col_info["ref"]
                py_type = f"{py_type} | None"
                fk = f"Field(default=None, " f'foreign_key="{ref_table}.{ref_col}")'
                default = f" = {fk}"
            elif col_info["nullable"]:
                # Nullable field
                py_type = f"{py_type} | None"
                default = " = None"
            else:
                # Required field
                default = ""

            if default:
                schema += f"    {col_name}: {py_type}{default}\n"
            else:
                schema += f"    {col_name}: {py_type}\n"

        # Add reverse relationships
        if table_name in references:
            for from_table, from_col in references[table_name]:
                from_parts = from_table.split("_")
                from_class = "".join(w.capitalize() for w in from_parts)
                rel_name = pluralize(from_table)
                rel = (
                    f'    {rel_name}: list["{from_class}"] = '
                    f'Relationship(back_populates="{table_name}")\n'
                )
                schema += rel

        # Add forward relationships (to referenced tables)
        for col_name, col_info in table_info["columns"].items():
            if col_info["ref"]:
                ref_table, ref_col = col_info["ref"]
                ref_parts = ref_table.split("_")
                ref_class = "".join(w.capitalize() for w in ref_parts)
                rel_name = pluralize(table_name)
                # Use forward reference only if needed
                rel = (
                    f"    {ref_table}: {ref_class} | None = "
                    f'Relationship(back_populates="{rel_name}")\n'
                )
                schema += rel

        schema += "\n"

    return schema


def main():
    """Main generation function."""
    config_dir = Path(__file__).parent
    dbml_file = config_dir / "schema.dbml"
    mermaid_file = config_dir / "schema.md"
    schema_file = config_dir / "schema.py"

    if not dbml_file.exists():
        print(f"Error: {dbml_file} not found")
        return

    print(f"Parsing {dbml_file}...")
    tables = parse_dbml(str(dbml_file))

    # Generate Mermaid ER diagram
    print("Generating Mermaid ER diagram...")
    mermaid = generate_mermaid_er(tables)

    # Generate SQLModel schema
    print("Generating SQLModel schema...")
    sqlmodel_schema = generate_sqlmodel_schema(tables)

    # Write Mermaid diagram
    mermaid_content = f"""# Entity Relationship Diagram

```mermaid
{mermaid}```

## Tables

"""
    for table_name, table_info in tables.items():
        mermaid_content += f"\n### {table_name.capitalize()}\n\n"
        mermaid_content += "| Column | Type | Nullable | Primary Key |\n"
        mermaid_content += "|--------|------|----------|-------------|\n"
        for col_name, col_info in table_info["columns"].items():
            nullable = "Yes" if col_info["nullable"] else "No"
            pk = "Yes" if col_info["pk"] else "No"
            row = f"| {col_name} | {col_info['type']} | {nullable} | {pk} |\n"
            mermaid_content += row

    with open(mermaid_file, "w") as f:
        f.write(mermaid_content)
    print(f"✓ Generated {mermaid_file}")

    # Write SQLModel schema
    with open(schema_file, "w") as f:
        f.write(sqlmodel_schema)
    print(f"✓ Generated {schema_file}")


if __name__ == "__main__":
    main()
